- name: Install Microk8s
  become: true
  community.general.snap:
    name: microk8s
    classic: true
    channel: "{{ microk8s_version }}"
    dangerous: false
- name: Create kubectl alias
  become: true
  community.general.snap_alias:
    name: "microk8s.kubectl"
    alias: "kubectl"
    state: present
  changed_when: false
- name: Create helm3 alias
  become: true
  community.general.snap_alias:
    name: "microk8s.helm3"
    alias: "helm"
    state: present
  changed_when: false
  when:
    - "'helm3' in microk8s_plugins"
    - microk8s_plugins.helm3
- name: Create config_dir for user
  become: true
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    owner: "{{ microk8s_user_name }}"
    group: "{{ microk8s_user_name }}"
    force: true
    recurse: true
    mode: "0750"
- name: Wait for microk8s to be ready
  become: true
  ansible.builtin.shell: "/snap/bin/microk8s.status --wait-ready --format yaml"
  args:
    executable: /bin/bash
  changed_when: false
  register: microk8s_status
  failed_when:
    - "'microk8s is running.' not in microk8s_status.stdout_lines"
    - microk8s_status.rc != 0
- name: Set current state fact
  ansible.builtin.set_fact:
    microk8s_status: "{{ microk8s_status.stdout | from_yaml }}"
