- name: Create group
  become: true
  ansible.builtin.group:
    name: "{{ microk8s_user_group }}"
    state: present
- name: Add the user to appending the group 'microk8s'
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ microk8s_user_group }}"
    append: true
  register: add_to_group_result

- name: Include reset connection tasks
  ansible.builtin.include_tasks: reset_connection.yml
  when: add_to_group_result.changed

- name: Install snap
  become: true
  ansible.builtin.apt:
    name: "{{ microk8s_inst_packages }}"
    state: present
    update_cache: true
    lock_timeout: 300
  when: ansible_os_family == "Debian"
- name: Get public IP
  community.general.ipify_facts:
  timeout: 20
