---
# handlers file for microk8s
- name: Refresh certificates
  become: true
  ansible.builtin.command:
    argv:
      - /snap/bin/microk8s
      - refresh-certs
      - --cert
      - ca.crt
  register: microk8s_cert
  changed_when: false
  failed_when:
    - "'The CA certificates have been replaced' not in microk8s_cert.stdout"
  retries: 5
  delay: 20
  until: "'The CA certificates have been replaced' in microk8s_cert.stdout"